### ISSUE TITLE
Error push

### ISSUE THREAD

**Issue by jcechavarri** [Exploratorio-DCC-PUC/Syllabus-2018-2#100]
Tratando de subir la tarea, al hacer push no se actualiza mi página en github (es como si no tuviera derechos para modificar).

Intenté borrar la carpeta y volver a clonarla. Al hacerlo se descarga con mis archivos nuevos, pero aún así en github no aparecen. 

*Edit: 
Al parecer es un error de github, como se deberá subir la tarea? https://status.github.com/messages*

**Comment by Mdelaf** [comment]
Efectivamente Github ha estado con problemas, pero ya deberían estar solucionados. De todas formas si de aquí a mañana siguiera mal avisaremos cómo entregar.
