### ISSUE TITLE
Pregunta 2

### ISSUE THREAD

**Issue by EstebanReyes1998** [Exploratorio-DCC-PUC/Syllabus-2018-2#102]
¿Podemos asumir que el input siempre tendrá por lo menos un carácter a y un carácter b, o debemos asumir que pueden haber palabras que no tengan a´s, o b´s, o palabras vacías?
¿En este caso, 0 es múltiplo de 2 y de 3?
Gracias

**Comment by Mdelaf** [comment]
No habrá palabras vacías, pero sí puede haber palabras que tienen solo letras `a` o solo letras `b`. En el enunciado hay ejemplos y se explica por qué deben ser aceptadas/rechazadas en cada caso. 

El cero sí lo consideramos como múltiplo 2 y de 3, y de cualquier número en general.
