### ISSUE TITLE
Definicion Formal \delta

### ISSUE THREAD

**Issue by felipegarcia98** [Exploratorio-DCC-PUC/Syllabus-2018-2#103]
En el enunciado, se menciona que debes definir formalmente a delta, pero, anteriormente, se señala como definición tanto a
![screenshot_1](https://user-images.githubusercontent.com/42228743/47337724-8a9a1a80-d66b-11e8-8cdb-a74fe67558fc.png)
como a 
![screenshot_2](https://user-images.githubusercontent.com/42228743/47337730-908ffb80-d66b-11e8-8bc2-09ee34df8ef3.png)

Cuál de las dos es correcta?

**Comment by Mdelaf** [comment]
Lo de arriba solo define el dominio y recorrido de la función delta. 

Se espera que en tu respuesta estén definidas las transiciones, como el ejemplo de abajo.
