### ISSUE TITLE
[No Ramo][Lichess]

### ISSUE THREAD

**Issue by tcperez** [Exploratorio-DCC-PUC/Syllabus-2018-2#105]
Hola
¿Cuál era el usuario de Lichess del profesor Nebil Kawas?
Gracias!

**Comment by nebil** [comment]
Hola, @tcperez. No recuerdo haber dicho cuál era mi nombre usuario de Lichess en clases. De todas formas, lo dejaré por [acá](https://lichess.org/@/alexcasablancas). Y en caso de que me envíes un _challenge_, preferiría que fuese en modo _blitz_ o _bullet_. :zap:
