### ISSUE TITLE
Ayudantía

### ISSUE THREAD

**Issue by iraraya** [Exploratorio-DCC-PUC/Syllabus-2018-2#108]
Hola, podrían subir alguna información de la ayudantía de ayer para realizar la tarea? 
gracias

**Comment by Dalal15** [comment]
Hola,

Ya se encuentra subida. Esta ayudantía tiene varios tips para la tarea y es más bien complementaria a las clases del profesor Marcos. Recomiendo entender las clases primero y luego ver la ayudantía.

Éxito en la tarea!
