### ISSUE TITLE
TC4

### ISSUE THREAD

**Issue by josefaespnza** [Exploratorio-DCC-PUC/Syllabus-2018-2#109]
Hola, como se puede guardar el archivo bpm como un archivo pdf. Saludos.

**Comment by Dalal15** [comment]
Eso depende de qué programa utilizaste para realizar la tarea. ¿Cuál usaste?

**Comment by adbakulic** [comment]
Yo estoy usando bpmn.io y al apretar el ícono para descargar como SVG, se me abre en los programas Ilustrator o con Atom, y se ven puras letras

**Comment by adbakulic** [comment]
Me pasó que con safari no me funcionó y me aparecieron solo letras. Después probé con google chrome y me funcionó descargar la imagen pero no se ven ciertas cosas, como líneas.
