### ISSUE TITLE
Actividad 1

### ISSUE THREAD

**Issue by lfuenzalida2** [Exploratorio-DCC-PUC/Syllabus-2018-2#11]
casi al inicio de la parte 1, cuando me dicen que debo ejecutar el comando 'nano nombre.md' a mi dice que ese comando no existe, que puedo hacer?

**Comment by lfuenzalida2** [comment]
ya lo arregle

**Comment by Mdelaf** [comment]
Hola,

Si arreglas tu error podrías aprovechar de decir cómo lo hiciste. Así cuando tus otros compañeros tengan el mismo problema pueden leer esta _issue_ y no tener que volver a preguntar.

Para los que tengan esta duda, esto suele ocurrir si intentan ejecutar `nano` desde el CMD o el Powershell, ya que `nano` no viene instalado en Windows. Por esta razón, al principio del enunciado se sugiere que usen _Git Bash_ o _Windows Subsystem for Linux_ que sí traen `nano` instalado.
