### ISSUE TITLE
TC4 respecto a horas

### ISSUE THREAD

**Issue by fivaldivia** [Exploratorio-DCC-PUC/Syllabus-2018-2#110]
Hola, quería saber si el horario es relevante ponerlo en el proceso. Me refiero a cuando describe que el chofer pasa a buscar al grupo a las 8:30 hrs. o 24:00 hrs. Gracias!

**Comment by Dalal15** [comment]
Hola,

Si es necesario, ya que son eventos de tiempo.
Saludos
