### ISSUE TITLE
TC4 Interacción con restaurant

### ISSUE THREAD

**Issue by pstassara** [Exploratorio-DCC-PUC/Syllabus-2018-2#111]
Hola, en la tarea no me queda claro si la interacción con el "Fogón Patagón" debe ser considerada como una interacción entre dos pools, o puede ser considerada simplemente como una actividad más que realiza el guía (por lo que no sería necesario tener un pool que fuese el restaurant). Gracias!

**Comment by jidiaz15** [comment]
Yo tengo la misma duda, ojalá pudieran responder porque es lo que me falta para terminar la tarea.

**Comment by Dalal15** [comment]
Puede ser considerada como una actividad más que realiza el guía. 
Saludos!

**Comment by NelsonIMA** [comment]
Solo para confirmar: Cuando el guía los acompaña al lugar de almuerzo y luego a las termas, se considera que van solo con él? o que son transportados por el chofer? yo creo no, ya que lo mencionan (chofer) para decir que regresan con el al hotel.

 Perdon por lo tarde  y gracias de antemano
