### ISSUE TITLE
TC4 interacción con pasajeros

### ISSUE THREAD

**Issue by adbakulic** [Exploratorio-DCC-PUC/Syllabus-2018-2#112]
Hola,
Cuando en el enunciado de la tarea piden que no mostremos la interacción del proceso con el grupo de pasajeros, ¿se refiere a que ni siquiera hagamos un pool de pasajeros?

**Comment by Dalal15** [comment]
Exacto!

**Comment by adbakulic** [comment]
Gracias!!

**Comment by adbakulic** [comment]
Gracias!!
