### ISSUE TITLE
TC4 sobre el primer issue 

### ISSUE THREAD

**Issue by adbakulic** [Exploratorio-DCC-PUC/Syllabus-2018-2#113]
Hola,
No han vuelto a responder el primer issue sobre la tarea. No me funcionó que se vieran las líneas al descargar el archivo svg, a pesar de que todo el resto se ve bien en la imagen. No se qué podrá ser, y ya traté de arreglarlo pero no he podido. Igual subí la imagen sin las líneas.
Muchas gracias!

**Comment by Dalal15** [comment]
Revisé tu repositorio de la tarea y la imagen es legible, así que no hay problema :)

**Comment by adbakulic** [comment]
Si la revisaste recién debe ser porque subí otra donde hice las líneas a mano. Espero que siga legible.
