### ISSUE TITLE
Actividad 3

### ISSUE THREAD

**Issue by aiduran** [Exploratorio-DCC-PUC/Syllabus-2018-2#12]
Hola! Cuando empecé la actividad 3, abrí la consola desde la misma carpeta resultados, cree los archivos .gitignore e hice el commit. Sin embargo, al parecer me equivoqué en esta parte y lo que hice fue simplemente borrar los archivos .gitignore que se crearon ¿Desde aquí, puedo continuar con mi tarea normalmente  o tengo que empezar de nuevo? Ya que no tengo claro si es que se aplicó el commit, entonces quiero volver a empezar la actividad 3.

**Comment by VinceValence** [comment]
Hola,

Revisé tu repositorio y a primera vista no vi nada extraño, por lo que asumo que tu problema está en tu repositorio local. Por favor revisa la guía de Git [aquí](https://github.com/Mdelaf/git-introduction-guide).

Siempre puedes volver al commit anterior, lo que podrás encontrar en la guía. Si tienes más dudas, continúa escribiendo por aquí.

**Comment by aiduran** [comment]
Volví al ultimo commit que es el de la actividad 2 y al hacer "git status" me aparecen los siguientes elementos:
        ../git status
        ../logs/
        LOGS.txt
        generated_code.py

**Comment by Mdelaf** [comment]
¿Al correr `git status` te aparece `../git status` como un archivo modificado? ¿O te equivocaste al escribir? 

Si quieres empezar la Actividad 2 desde cero, sigue los siguientes pasos:
1. Elimina tu repositorio local (borra la carpeta)
2. Clona de nuevo el repositorio.
3. Usa el comando `git revert c770117` (Cntrl + X para salir del editor) y luego `git push`

Con eso ya puedes empezar desde la actividad 2 como si no hubieras hecho nada.

**Comment by aiduran** [comment]
Me aparece ../git status debajo de untracked files en la carpeta resultados al poner el comando "git status". Lo que me interesa es empezar la actividad 3 desde cero, ¿puedo realizar los mismos pasos anteriores?

**Comment by Mdelaf** [comment]
Ya armaste un lío demasiado grande en tu repositorio local jajajaj. Mi recomendación es que sigas las instrucciones que te dije, vuelvas a hacer la actividad 2 y luego sigues con el resto.
