### ISSUE TITLE
actividad 4

### ISSUE THREAD

**Issue by smrebolledo** [Exploratorio-DCC-PUC/Syllabus-2018-2#13]
Al momento de escribir git reset HEAD^1 me dice esto:  _fatal: ambiguous argument 'HEAD1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'_
 Que hago mal o que puedo hacer?

**Comment by Mdelaf** [comment]
¿Qué sistema operativo tienes? ¿No será que te está tomando mal el caracter `^`? 

Intenta copiarlo de alguna parte o usar `HEAD~1`.
