### ISSUE TITLE
commits

### ISSUE THREAD

**Issue by adbakulic** [Exploratorio-DCC-PUC/Syllabus-2018-2#14]
Hola! 
Terminé mi tarea hace varios días, pero quería arreglar una de las actividades y al hacer push origin master se me borraron todos los nombres que les di a los commits en el repositorio,
por favor ayuda.

**Comment by Mdelaf** [comment]
Hola,

Estoy mirando tu repositorio en Github y puedo ver todos los commits que hiciste sin problemas. No entiendo a qué te refieres con que se borraron los nombres de los commits.

**Comment by adbakulic** [comment]
Si me di cuenta de que se pueden ver pero en el repositorio principal antes
me aparecían los commits,
Muchas gracias!
