### ISSUE TITLE
Sobre parte 2: Dashboard

### ISSUE THREAD

**Issue by malopez16** [Exploratorio-DCC-PUC/Syllabus-2018-2#16]
Hola!
Tengo dudas con respecto a la parte 2.
Se indica que se debe entregar una página web con algunas cosas, pero me quedaron algunas dudas de ciertos detalles:
1. ~~La web debe llevar los gráficos que obtuvimos anteriormente. Los subimos en forma de imagen o los debemos generar con javascript en la página también?~~ Edit: Acabo de notar que se menciona implícitamente al final de la parte 1.
2. Se solicita que la web sea responsive. Podemos hacerlo con Bootstrap para la alineación de los elementos o sólo usamos html? ¿(o usamos css directamente)?
3. Necesitan que se utilice javascript sólo para cargar los datos y que los mostremos en forma de tabla en html o que hagamos absolutamente todo lo relativo a las tablas en javascript y simplemente lo importemos en el html?

Gracias, saludos!

**Comment by flartur95** [comment]
2. Bootstrap it's an API of CSS, likely a big CSS ready, with a responsives types to use in your page.

**Comment by diflores** [comment]
Hola, vamos por partes:

1. Sí, se espera que exporten los gráficos a algún formato de imagen. También pueden exportarlos a SVG.
2. Pueden utilizar cualquier _framework_ para obtener esa parte del puntaje (Bootstrap, Semantic UI, Foundation, Skeleton, etc).
3. Se espera que obtengan la información de las tablas a partir de los csv (no que la escriban a mano, por ejemplo). No se me ocurre cómo hacer esto sin utilizar JavaScript. En lo que respecta a este tema, quiero agregar que no se les obliga a programar en JavaScript _vanilla_, pueden emplear jQuery o cualquier librería que les facilite el _parsing_ del archivo.

¡Saludos!

**Comment by malopez16** [comment]
Me quedó clarisimo. Gracias!
