### ISSUE TITLE
Sobre versión de python TG1

### ISSUE THREAD

**Issue by malopez16** [Exploratorio-DCC-PUC/Syllabus-2018-2#19]
Hola! Debemos usar la versión 3.7? 
Estoy teniendo muchísimos problemas de dependencias con esta versión :( , pero con la 3.6 me anda bien. 

Gracias :)

**Comment by VinceValence** [comment]
Hola,

Puedes usar la versión de Python que quieras que sea mayor a 3.4

**Comment by malopez16** [comment]
Oook! Graacias!
