### ISSUE TITLE
Problema actividad 2

### ISSUE THREAD

**Issue by nhbravo** [Exploratorio-DCC-PUC/Syllabus-2018-2#2]
Hola! Cuando hago `python3 actividad2.pyc` me dice 

> RuntimeError: Bad magic number in .pyc file

¿Cómo puedo arreglar esto o a qué se debe?

**Comment by Mdelaf** [comment]
Hola, 

El archivo `actividad2.pyc` es un archivo compilado de Python, por lo tanto debe ejecutarse con la misma versión de Python con la que se compiló. 

En el enunciado (al final de las Instrucciones) dice que para esta tarea usaremos Python en su versión 3.7, de modo que si usan otra versión van a obtener un `RuntimeError` al ejecutar el archivo `.pyc`.

Saludos.

**Comment by fnquinteros** [comment]
Hola! 

Me parece que en Ubuntu no ha salido una version estable de python 3.7 (al menos al usar `sudo apt-get install python3` me trata de instalar la 3.6.5, que ya tengo). De todas formas seguí [estos pasos](https://serverfault.com/questions/918335/best-way-to-run-python-3-7-on-ubuntu-16-04-which-comes-with-python-3-5) y lo logré instalar sin problemas. Ahí lo dejo por si alguien se topa con el mismo problema :sweat_smile: 

Saludos!

**Comment by robertov1** [comment]
Hola, estoy usando Windows subsystem for linux y tengo instalado python 3.7 (ninguna versión más). Y me dice RuntimeError: Bad magic number in .pyc file cuando pongo python3 actividad2.pyc

Que puede ser?

**Comment by fnquinteros** [comment]
Que te sale cuando escribes en consola python3 --version?

**Comment by robertov1** [comment]
En la de Windows subsystem for linux python 3.6.5 pero en Windows Powershell 3.7.0

**Comment by Mdelaf** [comment]
Hola,

Cuando usas WSL el comando usa la versión que tienes instalada en WSL (3.6), y cuando usas Powershell el comando usa la versión que tienes instalada en Windows (3.7). Como el nombre lo dice, el primero es un "subsistema" que vive dentro de Windows por lo tanto puede tener programas y archivos diferentes.

Instalar Python 3.7 en WSL es más complicado porque tienes que seguir las instrucciones que mencionó @fnquinteros, pero puedes correr el comando desde el Powershell y continuar con el resto de las actividades desde WSL.

Saludos.

**Comment by robertov1** [comment]
Ok, gracias!
