### ISSUE TITLE
[TG1] Parte 1 4)

### ISSUE THREAD

**Issue by malopez16** [Exploratorio-DCC-PUC/Syllabus-2018-2#20]
Hola!
En la pregunta 4 se indica que se debe obtener una tabla. Debemos dibujarla? O sólo obtenerla con la sugerencia que se indica?

Gracias!

**Comment by diflores** [comment]
Hola, Mauricio.

En esa parte, basta con mostrar en un `DataFrame` de `pandas` lo pedido, para luego exportar eso a un archivo .csv. 
Espero haber aclarado tu duda. Si no, por favor responde este mensaje.

¡Saludos!
