### ISSUE TITLE
[TG1] Generación "Aleatoria" puntos bip

### ISSUE THREAD

**Issue by malopez16** [Exploratorio-DCC-PUC/Syllabus-2018-2#21]
Hola!
Con respecto a la generación aleatoria del código del punto bip donde se realiza la transacción, creo que como está enunciado hay un problema: En realidad no debería ser una generación aleatoria del cógido del punto bip donde se realiza la transacción, sino que debería ser una **selección** aleatoria del código del punto bip, entre los puntos bip entregados al ppo. De lo contrario tendríamos gente que no carga en ningún punto existente. ¿Está correcto asumir eso entonces?

**Comment by diflores** [comment]
Hola,

En la tarea sí está contemplado que puedan existir puntos donde no se realice ninguna recarga (no tiene demasiado sentido, pero así fue pensado). Lo que se pide en esa parte es que generen 10000 transacciones, lo que involucra producir 10000 fechas aleatorias, 10000 puntos de recarga (con repetición, por supuesto, ya que 10000 > cantidad de puntos bip) y, finalmente, 10000 montos de recarga según las restricciones del enunciado.

¡Saludos!

**Comment by malopez16** [comment]
Entendido. Entonces es una **selección** aleatoria 10.000 veces entre los códigos de los puntos bip entregados, no una "generación" de tales códigos como dice en el enunciado. (Para poder generar una transacción)
Gracias!

**Comment by diflores** [comment]
Sí, es selección.

¡Gracias por darte cuenta del detalle, Mauricio! Lo voy a actualizar en el enunciado lo antes posible.

¡Saludos!
