### ISSUE TITLE
Problema Jupyter

### ISSUE THREAD

**Issue by jcechavarri** [Exploratorio-DCC-PUC/Syllabus-2018-2#22]
Hola!
Al intentar abrir jupyter notebook me tira error.

Intenté desinstalar jupyter vía pip y luego volver a instalarlo y sigo obteniendo el mismo error. También intente por Anaconda sin resultados. Agradecería ayuda

![image](https://user-images.githubusercontent.com/42159312/45047873-bb3cdb00-b050-11e8-9851-eef1117a556a.png)

**Comment by Dalal15** [comment]
Hola,

Podrías intentar desinstalando anaconda y volverlo a instalar. Al momento de instalarlo **no** selecciones la opción por _default_ cuando te mencione las variables de entorno, marca la otra alternativa.

Ojalá te funcione!

**Comment by jcechavarri** [comment]
@Dalal15 Tampoco funcionó, no se qué hacer

**Comment by VinceValence** [comment]
Hola,

Mira esta página

https://answers.microsoft.com/en-us/windows/forum/windows_8-performance/c-file-or-directory-is-corrupted-or-unreadable/1f1fd08d-f723-47aa-b0aa-71d276241f45

Y cuéntanos como te va probando las soluciones que dicen allí

**Comment by jcechavarri** [comment]
@VinceValence Muchas Gracias! Eso era!

**Comment by VinceValence** [comment]
De nada!
