### ISSUE TITLE
Códigos de locales

### ISSUE THREAD

**Issue by iraraya** [Exploratorio-DCC-PUC/Syllabus-2018-2#25]
Hola!
No entiendo como tomar los datos de la columna de códigos de los puntos bip, estando en un dataframe, para formar la lista aleatoria que necesito con ellos para el nuevo dataframe.
Saludos

**Comment by Jiruiz2** [comment]
Hola,
Busqué "Pandas Dataframe" en Google y me aparecieron muchas páginas que te podrían ser de ayuda para esta duda, tanto en inglés como en español. Te recomiendo revisar la documentación en internet y eso puede hasta resolver futuras dudas.
Saludos

**Comment by Jiruiz2** [comment]
Hola, 
Busqué en Google tu duda y me apareció este link: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sample.html, que creo responde tu duda.
Saludos

**Comment by iraraya** [comment]
Sí gracias! tenía el comando sample pero no logré sacar los datos, lo cual después resolví con otro comando.
Saludos
