### ISSUE TITLE
Archivos parte 1

### ISSUE THREAD

**Issue by jpmarin1** [Exploratorio-DCC-PUC/Syllabus-2018-2#26]
Hola!
quería saber si al repositorio se sube sólo el jupyter o también los gráficos y csv creados?

**Comment by Jiruiz2** [comment]
Hola, 
En la parte 1 solo debes subir el archivo .ipnyb y este debe ser capaz de crear el archivo pedido cuando lo ejecutemos a la hora de corregir.
Saludos

**Comment by jpmarin1** [comment]
gracias!
