### ISSUE TITLE
Gráficos parte 1

### ISSUE THREAD

**Issue by jpmarin1** [Exploratorio-DCC-PUC/Syllabus-2018-2#28]
![montos_por_mes](https://user-images.githubusercontent.com/42441095/45260054-00477100-b3b3-11e8-97cc-65d954fc4ca4.png)
Hola! en el jupyter me dan bien todos los gráficos, pero copié el código entero a python y este gráfico se sobrepuso, por qué puede ser esto? no se como arreglarlo :(

**Comment by diflores** [comment]
Hola,

Prueba realizar los gráficos en celdas distintas de tu *jupyter notebook*.

¡Saludos!
