### ISSUE TITLE
Error Qt platform plugin

### ISSUE THREAD

**Issue by LaySofia** [Exploratorio-DCC-PUC/Syllabus-2018-2#29]
Hola, al tratar de abrir el Anaconda Navigator me tira este error:

![image](https://user-images.githubusercontent.com/42525944/45260101-19045680-b3b4-11e8-8894-bf65e1f31b7b.png)

Ya he tratado reinstalando varias veces, cambiando la opción predeterminada de las variables de entorno, restaurando el sistema (el cual me tiró error) y viendo si habían archivos corruptos (los cuales no habían).

**Comment by Jiruiz2** [comment]
Hola,
Revisa este link que encontré en internet y avísame si te funciona la solución que plantean https://github.com/ContinuumIO/anaconda-issues/issues/1270
Saludos
