### ISSUE TITLE
Tablas y csv

### ISSUE THREAD

**Issue by iraraya** [Exploratorio-DCC-PUC/Syllabus-2018-2#30]
Hola, tengo dudas de formalidad en las tablas y archivos creados, como por ejemplo:
1. ¿Debo preocuparme de los índices que se ponen por default en las tablas de dataframe, los cuales parten en 0?.
2. Los archivos csv, ¿deben contener los encabezados o nombres de las columnas?
3. En el último csv, de ranking de comunas según totalidad de monto, ¿se deben incluir dichos montos o sólo los nombres de las comunas?
4. En el punto 1, al hacer un data frame y un gráfico en el mismo input de jupyter, la tabla pierde el formato y me queda como en la foto. ¿Cómo puedo arreglar esto?

Saludos y gracias
![a1](https://user-images.githubusercontent.com/42379552/45265612-ff025c80-b423-11e8-8605-23d895c9df72.png)

**Comment by diflores** [comment]
Hola,

1. No te preocupes por los índices hasta que exportes a csv. Ahí, deberías usar `.to_csv("nombre_archivo", index=False)`.
2. Es lo ideal, pues deberían mostrarse cuando hagas la parte 2.
3. Comuna y montos.
4. Prueba agregando la línea `from IPython.display import display` y luego, cuando quieras imprimir un DataFrame, usa `display(nombre_dataframe_aquí)`.

¡Saludos!

**Comment by iraraya** [comment]
Gracias!
