### ISSUE TITLE
entregable jupyter

### ISSUE THREAD

**Issue by pongmaniatic** [Exploratorio-DCC-PUC/Syllabus-2018-2#31]
yo ya he hecho el trabajo pesado de calcular los números y tal como piden, la tabla de 10000 recargas y todos eso, la tabla de las 5 comunas y sus archivos csv. pero no entiendo a que se refiere con tener un entregable en jupyter, tampoco entiendo como quieren que haga el gráfico en torta. tengo las tablas csv y los archivo py con como lo hice en el repositorio, no entiendo como tenerlo presentable. muchas gracias

**Comment by jmndoza** [comment]
Hola! (no soy ayudante)
En tu repositorio hay 3 carpetas, dentro de '/parte_1' hay un archivo llamado Parte_1.ipynb en el que debes entregar el codigo

**Comment by pongmaniatic** [comment]
oh muchas gracias, ahora lo entiendo gracias por tu ayuda.

**Comment by pongmaniatic** [comment]
estoy intentando poder poner mis cosas en el la parte_1 pero no encuentro la forma correcta, intente poniendo editar, pero se me hace si cambio algo lo arruino, no se si hay que abrirlo de alguna forma en especifico

**Comment by pongmaniatic** [comment]
lo logre abrir para editar gracias

**Comment by jmndoza** [comment]
debes abrirlo con jupyter notebook (http://jupyter.org/install)
