### ISSUE TITLE
Data base

### ISSUE THREAD

**Issue by lfuenzalida2** [Exploratorio-DCC-PUC/Syllabus-2018-2#32]
Estoy teniendo problemas con la Parte 1 donde tengo que plotear los graficos, quise usar altair, pero no entiendo como usarlo, mi problema es que no se como hacer que mi información (lo que viene antes en la tarea) sea utilizado como informacion para plotear

**Comment by jmndoza** [comment]
Hola! (No soy ayudante)

No utilice Altair, pero revisé un poco y acá está casi todo lo necesario 
https://altair-viz.github.io/getting_started/starting.html para utilizarlo con pandas

Pd: Aunque descubrí que pandas ya trabaja con mathplotlib, por lo que crear un gráfico de un dataframe o serie es tan simple como aplicar .plot(*argumentos)

**Comment by lfuenzalida2** [comment]
Muchas gracias! con eso pude aprender como utilizar Altair, pero el ahora me tira un error cuando trato de hacer el plot, incluso trate con el ejemplo que sale ahi e igual me tira el error.
![captura de pantalla 36](https://user-images.githubusercontent.com/42476356/45269221-d3519780-b460-11e8-9f3d-650c7beea2d1.png)

**Comment by jmndoza** [comment]
intenta agregar esta linea: 
alt.renderers.enable('notebook')

**Comment by lfuenzalida2** [comment]
no me funciona...
