### ISSUE TITLE
hora de entrega?

### ISSUE THREAD

**Issue by pongmaniatic** [Exploratorio-DCC-PUC/Syllabus-2018-2#33]
hola, note que la tarea solo dice que la entrega es este lunes, pero no dice la hora, se tiene que asumir que la fecha limite es el lunes a las 0:01 o 23:59 horas?

**Comment by jmndoza** [comment]
Según el readme es hasta las 23:59 del 10 de septiembre

**Comment by diflores** [comment]
Hola,

Se entrega mañana a las 23:59. ¡Gracias Jerry por responder!

¡Saludos!

**Comment by Crespy98** [comment]
hola, puedo usar la librería os ?

**Comment by IchottMano** [comment]
@StroveLight si puedes usar time, pero no puedes usar deepcopy.
@Crespy98 Para que quieres usarla?
