### ISSUE TITLE
parte 2

### ISSUE THREAD

**Issue by josefaespnza** [Exploratorio-DCC-PUC/Syllabus-2018-2#34]
Hola, tengo la duda de en que parte se debe hacer la pagina web dado que nos entregan un script js y uno css y el index. Y que es lo que se tiene que subir finalmente. Gracias de antemano.

**Comment by Mdelaf** [comment]
Hola, 

Recuerda que la página web se compone de varios archivos. El archivo `index.html` define la estructura de tu página, el archivo `style.css` define el estilo y el archivo `script.js` define su comportamiento. 

Para que tu página quede bien hecha y cumpla con todo lo que se pide, deberás modificar estos tres archivos y subirlos a tu repositorio. También puedes agregar otros si lo estimas conveniente. 

Todos los archivos de la página deben estar dentro de la carpeta `parte_2` de tu repositorio.

Saludos.
