### ISSUE TITLE
Tablas HTML

### ISSUE THREAD

**Issue by iraraya** [Exploratorio-DCC-PUC/Syllabus-2018-2#36]
Hola
He intentado de muchísimas formas hacer las tablas en la página web a partir de los csv y aún no me resulta. Quería saber si los csv tienen que tener la info en sus columnas o sólo separadas por comas, ya que eso puede ser un factor, y aprovecho de preguntar por algún tip para hacerlo, dado que en internet entregan puros javascripts engorrosos y con librerías extrañas.
Saludos!

**Comment by Mdelaf** [comment]
Hola,

Los archivos CSV no son más que archivos de texto con valores separados por comas. No existe un estándar oficial para estos archivos. 

Como los CSV son archivos de texto, puedes leerlos desde Javascript de forma similar a como lo haces en Python. Por ejemplo, [en esta pregunta](https://stackoverflow.com/questions/14446447/how-to-read-a-local-text-file) se muestran algunas alternativas a cómo hacerlo.

Saludos.

**Comment by iraraya** [comment]
OK ahí lo logré pero usando scripts que están en internet. ¿Es válido subirlos con mi tarea? ¿Como los "cito"?
Gracias y saludos

**Comment by diflores** [comment]
Hola,

Basta con escribir al inicio de tu código o del extracto de código que sacaste de internet la fuente del recurso externo.

¡Saludos!
