### ISSUE TITLE
Tablas en Chrome

### ISSUE THREAD

**Issue by mpbosnic** [Exploratorio-DCC-PUC/Syllabus-2018-2#37]
Hola, 
Cuando intento cargar la página html en Google Chrome me sale el siguiente error:
> jquery.min.js:4 Failed to load file:///C:/Users/Milan/Downloads/bip/top_5_puntos.csv: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

Pero cuando abro la página con Microsoft Edge la pagina carga bien. Intenté buscando en internet pero me confundí más ¿Saben cómo solucionarlo?

**Comment by diflores** [comment]
Hola,

La mejor solución es utilizar un servidor local. Montar uno es bastante sencillo de lograr en Python.
Solo debes pararte en la carpeta donde se encuentre tu index.html y ejecutar lo siguiente:

```python -m http.server```

Luego, tu página debería verse en 0.0.0.0:8000 o localhost:8000.

¡Saludos!

**Comment by Mdelaf** [comment]
Los navegadores más modernos no permiten leer del sistema local de archivos directamente por un tema de seguridad. A eso se debe el error que te muestra Google Chrome.

Para solucionarlo puedes montar un pequeño servidor como explica Daniela y así servir los archivos CSV mediante HTTP.

**Comment by mpbosnic** [comment]
Abrí el servidor y si abro el html directamente desde el servidor funciona perfecto. Pero cuando lo abro desde la carpeta normal me tira el siguiente error

> Failed to load http://127.0.0.1:8000/top_5_puntos.csv: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

Gracias!

**Comment by diflores** [comment]
> si abro el html directamente desde el servidor funciona perfecto
¿Con esto te refieres a que ejecutas en servidor desde la carpeta de tu `index.html`? Si la respuesta es afirmativa, puedes dejarlo así.

¡Saludos!

**Comment by mpbosnic** [comment]
Si, cuando pongo en el navegador http://127.0.0.1:8000, se abre el index.html y funciona bien.
Gracias!

**Comment by Mdelaf** [comment]
Si escribes en tu navegador la URL [http://127.0.0.1:8000/index.html](http://127.0.0.1:8000/index.html) debería funcionarte bien. 

Si abres el archivo `index.html` directamente de la carpeta, ya no estás usando el protocolo HTTP, sino que el sistema de archivos (`file://.../index.html`) y vas a recibir ese error porque estas intentando obtener el archivo `.csv` desde un dominio diferente al del servidor. Esto no está permitido por la [política de mismo origen](https://en.wikipedia.org/wiki/Same-origin_policy).

Para hacer una excepción a la política del mismo origen, se puede usar el mecanismo [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) que define algunos _headers_ para hacer _requests_ entre dominios distintos. Esto es lo que sugiere el error que mencionaste.

Para tu tarea trabaja directamente desde la [http://127.0.0.1:8000/index.html](http://127.0.0.1:8000/index.html) y no tendrás problemas. Debes aclarar también en tu README la forma de probar tu página.

¡Suerte!

**Comment by perezpefaur** [comment]
Me ayudó el link! Gracias!!
