### ISSUE TITLE
Cambiar nombre en .ipynb

### ISSUE THREAD

**Issue by EstebanReyes1998** [Exploratorio-DCC-PUC/Syllabus-2018-2#38]
Sonará muy extra, pero como puedo colocar mi nombre en el archivo .ipynb ?

**Comment by diflores** [comment]
Hola, Esteban,

¿Te refieres a cambiarle el nombre al archivo? Eso se hace como lo harías
con cualquier otro archivo. Si te refieres a escribir texto en Markdown
dentro de tu archivo, lo que debes hacer es crear una nueva celda y hacer
que sea de tipo Markdown (puedes lograr esto haciendo click en la celda y
luego apretando Esc y después la tecla M).
