### ISSUE TITLE
Instalar Sqlite

### ISSUE THREAD

**Issue by amaiajuanchuto** [Exploratorio-DCC-PUC/Syllabus-2018-2#39]
Seguí todos los pasos que salían en la pagina para descargar sqlite, pero cuando lo intento abrir me sale que "No se puede ejecutar esta aplicación en el equipo", no se porque no me funciona, tengo Windows 10, no se si eso influye en algo. Gracias.

**Comment by Mdelaf** [comment]
Hola,

Necesitamos más información para poder ayudarte. ¿De dónde lo descargaste exactamente? ¿Lo descargaste como un instalador para Windows (archivo ejecutable) o en algún otro formato? ¿Tu sistema operativo es de 64 bits? ¿Y el instalador?
