### ISSUE TITLE
inicio actividad 2

### ISSUE THREAD

**Issue by smrebolledo** [Exploratorio-DCC-PUC/Syllabus-2018-2#4]
Hola, no sé como partir la actividad 2 en Windows por que con todo lo que escribo me aparece  _command not found_

**Comment by Mdelaf** [comment]
Hola,

Te recomiendo revisar [la última issue que publicamos](https://github.com/Exploratorio-DCC-PUC/Syllabus/issues/5), particularmente en la sección 3.1 o 3.2. 

Saludos.
