### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by iraraya** [Exploratorio-DCC-PUC/Syllabus-2018-2#40]
Hola, tengo hecho el mapa, pero para activarlo en la página web, me pide crear una cuenta en Google Cloud Platform, con datos de facturación y todo, para obtener una clave o API key. ¿Por casualidad tienen un API key que se pueda utilizar para activar el mapa y no tener que hacer todo este proceso?
Saludos y gracias

**Comment by diflores** [comment]
Hola,

Estuve leyendo y al parecer se necesita una cuenta con facturación activada (lo que implica tener tarjeta de crédito). Te recomiendo usar [Leaflet](https://leafletjs.com/examples/quick-start/), que es gratis. Si encuentras una forma de usar Google Maps sin tarjeta de crédito, sería ideal que la compartieras con tus compañeros.

**Comment by jifernandez4** [comment]
Hola, tengo el mismo problema, pero me tira error 
![image](https://user-images.githubusercontent.com/53873922/63724342-8576a080-c825-11e9-99a8-b806099096b9.png)
