### ISSUE TITLE
Mapa

### ISSUE THREAD

**Issue by mpbosnic** [Exploratorio-DCC-PUC/Syllabus-2018-2#41]
Hola, es necesario que el mapa sea programado en javascript o se puede usar cualquier forma que incluya un mapa en la página? Gracias!

**Comment by diflores** [comment]
Hola,

Lo ideal es usar JavaScript para cargar los pines en el mapa, ¿qué alternativa tienes en mente?

**Comment by mpbosnic** [comment]
Tenia pensado crear el mapa mediante la plataforma que ofrece Google Maps y hacer que se abra en el html poniendolo como url.

**Comment by diflores** [comment]
Hola,

Eso no es lo que se espera. La idea es que cargues los pines con JavaScript.

¡Saludos!

**Comment by mpbosnic** [comment]
Ok gracias
