### ISSUE TITLE
Tarea Chica 2

### ISSUE THREAD

**Issue by matumartinez** [Exploratorio-DCC-PUC/Syllabus-2018-2#42]
¿Se puede consultar la base de datos usando el módulo sqlite3 de python, o hay que usar solo sqlite?

**Comment by Dalal15** [comment]
Se recomienda utilizar sqlite. Sin embargo, al momento de corregir revisaremos que tu consulta escrita en tu `Readme.md` entregue el output esperado, por lo que puedes ocupar ese módulo siempre y cuando respete la sintaxis y genere el resultado correcto.

Saludos!
