### ISSUE TITLE
Errata Enunciado TC2

### ISSUE THREAD

**Issue by fnquinteros** [Exploratorio-DCC-PUC/Syllabus-2018-2#43]
Hola! La tabla Tracks tiene un atributo llamado Milliseconds que en el enunciado sale nombrada con una sola "L" (Miliseconds). Esto trae problemas al realizar la 3era consulta :sweat_smile: Si pudieran editar el enunciado, sería fantástico :smiley: De antemano gracias!

Saludos!

**Comment by Jiruiz2** [comment]
Hola, 
El enunciado actualizado ya se encuentra subido.
Muchas gracias por el aviso.
