### ISSUE TITLE
Ruta de archivo csv

### ISSUE THREAD

**Issue by Dnpoblete** [Exploratorio-DCC-PUC/Syllabus-2018-2#44]
Hola, he estado buscando por mucho rato como encontrar la ruta correcta para subir el archivo csv como tabla con javascript y ninguno me sirve, como puedo encontrar el correcto?
Gracias

**Comment by diflores** [comment]
Hola,
Perdón la demora, no me llegó la notificación de esta _issue_. Por lo que vi en tu repositorio, la ruta que debes poner es `js/script.js`.

Saludos.

**Comment by Dnpoblete** [comment]
Hola si eso ya lo puse, me referia a la ruta del csv.

**Comment by diflores** [comment]
No entiendo bien a qué te refieres con ruta... ¿quieres decir dónde ponerlo? Ojalá en alguna parte a la que puedas acceder desde la carpeta de la parte 2. Podría ser en la raíz de la carpeta parte 2 y luego lo llamas como `"../nombre_de_tu_csv.csv"` (asumiendo que el _script_ desde donde lo cargas está en `parte_2/js/`).

**Comment by Dnpoblete** [comment]
Si eso hice y no se porque no me abre, los csv estan en la carpeta parte 2
y el js tambien

**Comment by diflores** [comment]
Si haces click derecho en tu página abierta en el navegador y luego aprietas "Inspeccionar elemento", y, finalmente, "Consola" podrás ver tu error.

**Comment by Dnpoblete** [comment]
2018-09-11 23:43 GMT-03:00 Daniela Flores <notifications@github.com>:
