### ISSUE TITLE
No puedo instalar pandas ni matplotlib

### ISSUE THREAD

**Issue by cncosta** [Exploratorio-DCC-PUC/Syllabus-2018-2#45]
llevo todo el dia tratando de instalar pandas y matplot lib pero no puedo instalar las librerías: me sale lo siguiente para cuando trato de instalar matplotlib, me sale lo mismo cuando trato de instalar pandas, he tratado de muchas maneras pero nunca puedo 
![captura de pantalla 2018-09-11 a la s 18 33 30](https://user-images.githubusercontent.com/42576884/45389071-3d00ab80-b5f1-11e8-89db-5fd9333d6abd.png)

**Comment by diflores** [comment]
Hola,

En primer lugar, debes usar python 3 y no python 2.7. Puedes descargar dicha versión de Python desde su página oficial. Luego intenta escribir `sudo pip3 install numpy scipy matplotlib`. El sistema te pedirá la clave de tu computador.

¡Saludos!
