### ISSUE TITLE
Repositorio

### ISSUE THREAD

**Issue by adbakulic** [Exploratorio-DCC-PUC/Syllabus-2018-2#46]
Hola! Ya tengo lista la tarea pero tengo un problema al momento de subirla. A través de la terminal me meto a la carpeta clonada, pero al hacer git status me aparece el siguiente error:
fatal: not a git repository (or any of the parent directories): .git

**Comment by diflores** [comment]
Hola,

¿Puedes decirme qué te sale en la terminal al escribir `pwd`?

**Comment by adbakulic** [comment]
User\antobakulic\Desktop\tarea-grande-1-adbakulic-master que es la carpeta clonada

**Comment by diflores** [comment]
Hola,
Por favor intenta lo siguiente:

```
cd
cd Desktop
git clone https://github.com/Exploratorio-DCC-PUC/tarea-grande-1-adbakulic.git
cd tarea-grande-1-adbakulic
open .
```

Se abrirá una ventana del Finder, pero no cierres la ventana de la terminal. Pon tus archivos de la tarea en las carpetas que correspondan y luego, desde la ventana de la terminal puedes usar los comandos `add`, `commit` y `push`. Tal como hiciste para la tarea chica 1.

¡Saludos!

**Comment by diflores** [comment]
@adbakulic ¡Por favor avísanos si te funcionó!

**Comment by adbakulic** [comment]
al escribir cd .. y poner pwd quedo en /Users/antobakulic/Desktop y al escribir cd Desktop me aparece esto:
-bash: cd: Desktop: No such file or directory

**Comment by adbakulic** [comment]
debe ser porque ya estoy en Desktop yo creo

**Comment by adbakulic** [comment]
creo que me funcionó pero fue porque cree una carpeta llamada tarea-grande-1-adbakulic que antes no tenía

**Comment by diflores** [comment]
Sí, sorry, quise decir solo `cd`, pero, ya que estás en Desktop, ejecuta desde `git clone ...`

EDIT: qué bacán que te haya funcionado. ¡Éxito!

**Comment by adbakulic** [comment]
No, solo me funciona llegar al directorio:
/Users/antobakulic/Desktop/tarea-grande-1-adbakulic-master/tarea-grande-1-adbakulic
pero de nuevo puse git status y me apareció:
fatal: not a git repository (or any of the parent directories): .git

**Comment by adbakulic** [comment]
me funcionó ahora si con lo que me dijiste!! Muchas gracias, te pasaste

**Comment by adbakulic** [comment]
perdón pero al final no me resultó
puedo usar las funciones de git pero no se sube nada y me aparece lo siguiente:
al hacer commit me aparece:
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
y al hacer push:
Everything up-to-date

**Comment by diflores** [comment]
¿Pusiste tus archivos en esa carpeta?

**Comment by adbakulic** [comment]
sii

**Comment by diflores** [comment]
¿En qué carpeta estás (`pwd`)?
¿Qué sale al escribir `git status`?

**Comment by adbakulic** [comment]
estoy en la carpeta /Users/antobakulic/Desktop/tarea-grande-1-adbakulic
Lo que es raro porque en Desktop tengo una carpeta llamada tarea-grande-1-adbakulic-master y dentro de ésta se encuentra la otra carpeta llamada tarea-grande-1-adbakulic. Pero al escribir el código que me pusiste al hacer pwd estoy en esta: /Users/antobakulic/Desktop/tarea-grande-1-adbakulic
y al hacer git status me aparece:
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

**Comment by adbakulic** [comment]
se me ocurre que tal vez si pongo mis archivos en area-grande-1-adbakulic-master y luego hago push se suban, ya que por lo que entiendo lo que me aparece es como si ya tuviera todo subido

**Comment by diflores** [comment]
Hola de nuevo,

Creo que ya sé qué pasa: la carpeta `tarea-grande-1-adbakulic-master` parece haber sido descargada de la página de GitHub mediante los botones Open in Desktop, o bien Download as ZIP. Esto quiere decir que no clonaste el repositorio debidamente. Los pasos a seguir eran similares a los de la tarea chica 1.

Los comandos que te di eran para que clonaras tu repositorio correctamente en la carpeta Desktop y aparentemente funcionó, pues ya tienes la carpeta `tarea-grande-1-adbakulic`. Es ahí donde tienes que copiar los archivos y no en `Desktop/tarea-grande-1-adbakulic-master/tarea-grande-1-adbakulic`. Una vez que se detecten los cambios en la carpeta adecuada, podrás ejecutar `add`, `commit` y `push`.

**Comment by adbakulic** [comment]
si fue eso, pero los comandos que me diste funcionaron luego de que yo creara una nueva carpeta llamada tarea-grande-1-adbakulic, no se si esto afectará.

**Comment by diflores** [comment]
No estoy entendiendo, ¿creaste esa carpeta a mano o se creó al hacer `git clone`?

**Comment by adbakulic** [comment]
Ya encontre la carpeta tarea-grande-1-adbakulic creada gracias a tus comandos, la cual está casi vacía, le faltan los archivos que yo realicé. 
Ahora la idea es que en esta carpeta casi vacía yo agregue mis archivos trasladándolos o desde la terminal con git?

**Comment by diflores** [comment]
Lo más fácil es mover los archivos a esa nueva carpeta vía Finder y luego, desde la terminal, subirlos con git.

**Comment by adbakulic** [comment]
Muchas gracias por toda tu ayuda!!!! Voy a ver si me funciona!
