### ISSUE TITLE
Como poner el nombre de los mese abajo del grafico

### ISSUE THREAD

**Issue by cncosta** [Exploratorio-DCC-PUC/Syllabus-2018-2#47]
tengo este codigo:
mensuales= total_mensual.groupby(["Mes"]).size()
grafico_mesual= total_mensual.plot(title="Cargas Por Mes",kind= "bar" )

grafico_mesual.set_xlabel("meses")
grafico_mesual.set_ylabel("monto total")
plt.show()
Como hago para que salga el nombre de los meses abajo?
mi archivo csv est escrito de la siguiente forma:
Mes, Total 
ENERO,10863390
FEBRERO,11281910
MARZO,10790030
ABRIL,10991030
MAYO,10960920
JUNIO,11196660
JULIO,10733930
AGOSTO,10812350
SEPTIEMPRE, 10953170
OCTUBRE,10864330
NOVIEMBRE,10774640
DICIEMBRE,10789280
pero el gráfico aparece de la siguiente manera
![captura de pantalla 2018-09-11 a la s 20 10 13](https://user-images.githubusercontent.com/42576884/45392637-bc48ac00-b5fe-11e8-9a6a-a991bff77933.png)
también como hago para que no este elevado a las potencias de e en el eje y

**Comment by diflores** [comment]
Hola,

Creo que [esto](https://stackoverflow.com/questions/48413069/plot-x-axis-with-string-array-as-in-the-same-order-in-original-array-and-not-sor) puede servirte.
