### ISSUE TITLE
Error al instalar SQLite

### ISSUE THREAD

**Issue by EstebanReyes1998** [Exploratorio-DCC-PUC/Syllabus-2018-2#48]
Basicamente, en la tarea chica 2, en la parte donde tenemos que instalar SQLite, sigo las instrucciones de la pagina http://www.sqlitetutorial.net/download-install-sqlite/; sin embargo, a la hora de realizar el paso:

Second, type sqlite3 and press enter, you should see the following output:

no me reconoce sqlite3 como comando, en ninguna versión de windows del programa que descargue. ¿Que estoy haciendo mal?.
gracias

**Comment by EstebanReyes1998** [comment]
Ignoren mi pregunta, lo estaba realizando mediante GitBash, pero realmente se hace con la CMD

**Comment by malopez16** [comment]
Hola!
Debe realizarse sólo con Javascript.

**Comment by fmartint** [comment]
Hola! Puedo hacer el botón sin Javascript? me refiero a usar solamente html y css.

**Comment by malopez16** [comment]
Hola!
Si se te hace más fácil, lo puedes hacer sin Javascript. Pero ojo, no se puede usar ningún framework de html ni css, ni de ningún tipo. Sólo código directo en HTML/CSS/JS. Si cumples con eso, no hay problema :)

Saludos
