### ISSUE TITLE
Parte 1, tarea chica 2

### ISSUE THREAD

**Issue by amaiajuanchuto** [Exploratorio-DCC-PUC/Syllabus-2018-2#49]
En la parte 1 se pide relacionar las tablas con un diagrama entidad relación. Tengo una duda porque cuando busco en google que es, me salen como diagramas basicos como mapa conceptual. y no se si eso hay que hacer o no. Gracias.

**Comment by Dalal15** [comment]
Hola!

En la clase de bases de datos se mostró la sintaxis de un diagrama entidad relación, explicado con un ejemplo. La clase ya se encuentra en el repositorio por lo que puedes revisarla para aclarar tus dudas.

Hoy en ayudantía también explicaremos diagrama entidad relación :)

**Comment by nhbravo** [comment]
No se entiende nada del ejemplo de la clase y el enunciado es poco claro. Por favor aclarar para los que no podemos ir a la ayudantía.

**Comment by Dalal15** [comment]
En el enunciado se pide literalmente un diagrama entidad relación. Básicamente un diagrama de entidad relación busca mostrar el modelo de datos, lo cual no incluye acciones, estados o funciones. Entonces, lo único  importante son los objetos de interés, que atributos tienen, y como se relacionan entre ellos,

La sintaxis está en la clase, o la puedes buscar [diagrama entidad relación](https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model). 

Espero haber aclarado tus dudas, de igual forma subiré la ayudantía de hoy en el repositorio del curso.

**Comment by malopez16** [comment]
Hola! 
El tamaño que viene por default para cuando pones un gráfico en el HTML es el mismo tamaño que mencionaste que estás editando, por lo que en realidad lo configuras tú.
Idealmente se deberían poder ver los 5 en la pantalla, por lo que se busca un tamaño razonable, si a eso te refieres.

Saludos!
