### ISSUE TITLE
Tarea grande 1

### ISSUE THREAD

**Issue by lfuenzalida2** [Exploratorio-DCC-PUC/Syllabus-2018-2#50]
tuve un problema y subi mal la tarea grande 1, la subi el martes alrededor de las 5 y quedo guardada en mi repositorio personal, trate de subirla la repositorio correspondiente pero no me deja, clone el archivo y puse toda la tarea dentro, pero sigue sin subirse al repositorio correspondiente, se sube a mi repositorio personal

**Comment by lfuenzalida2** [comment]
ya lo arregle, recien pude subirlo, pero no se cual fue el problema que me impedía subir la tarea al repositorio correspondiente, de hecho hice los mismos pasos, pero en una carpeta completamente nueva

**Comment by diflores** [comment]
No funcionaba porque clonaste el repositorio correcto dentro del repositorio que creaste y donde entregaste errónamente la tarea. Por eso, al hacer push, los archivos fueron subidos al repositorio incorrecto.

**Comment by diflores** [comment]
¡Hola!

Ese fue un error de enunciado. Los días de la semana son de lunes a domingo.

¡Saludos!
