### ISSUE TITLE
Tarea chica 2

### ISSUE THREAD

**Issue by rzyuras** [Exploratorio-DCC-PUC/Syllabus-2018-2#51]
![screen shot 2018-09-12 at 3 49 37 pm](https://user-images.githubusercontent.com/42726213/45446575-975a4480-b6a3-11e8-9283-9a6387c82c82.png)
Creo que no se me creo correctamente el repositorio, al entrar muestra lo que se ve en la foto. Como lo soluciono ?

**Comment by Dalal15** [comment]
Hola!

Haz `git pull` en tu repositorio mediante consola. La verdad no sé porque tu repositorio no se creo de manera correcta, pero subí manualmente todo lo necesario para que puedas realizar tu tarea.

Saludos!
