### ISSUE TITLE
Consulta 2

### ISSUE THREAD

**Issue by iraraya** [Exploratorio-DCC-PUC/Syllabus-2018-2#54]
Hola
No entiendo bien la consulta 2 de la tarea chica. Los 10 compositores, ¿deben ser diferentes, o pueden repetirse para distintas canciones?¿debe ponerse una canción para cada compositor o todas las de él que estén en dicha lista?.
Saludos y gracias

**Comment by Mdelaf** [comment]
Yo diría que no importa que se repitan, y para cada uno pongas una sola canción. De todas formas esperemos la confirmación de @Dalal15.

Aprovecho de comentarte que en el archivo README se espera que escribas la consulta SQL para cada caso, y no el resultado de esa consulta (porque veo en tu repositorio que estas escribiendo el resultado).

Saludos.

**Comment by iraraya** [comment]
okey, gracias
