### ISSUE TITLE
No puedo instalar sqlite

### ISSUE THREAD

**Issue by vperez2** [Exploratorio-DCC-PUC/Syllabus-2018-2#56]
Todavía no puedo instalar sqlite en mi windows 10. Seguí las instrucciones de la página y al poner el comando sqlite3 no lo reconoce, por qué puede ser??

**Comment by Mdelaf** [comment]
Debes asegurarte que la carpeta donde instalaste sqlite esté en el `PATH`. 

El `PATH` es una variable de entorno que contiene una lista de directorios. Su función principal es que todos los archivos ejecutables dentro de estos directorios se pueden acceder desde la consola sin tener que escribir su ruta completa.

[En este enlace](https://parzibyte.me/blog/2017/12/21/agregar-directorio-path-windows/) puedes ver cómo agregar un directorio al `PATH`. Recuerda que debes reiniciar la consola cuando hagas una modificación en las variables de entorno.
