### ISSUE TITLE
tarea chica 2

### ISSUE THREAD

**Issue by josefaespnza** [Exploratorio-DCC-PUC/Syllabus-2018-2#59]
Hola, para la consulta 3 no me resulta filtrarlos por la primera letra cuando le doy la condicion where tracks.name="S" no me muestra nada. No se de que otra forma se puede hacer o que estoy haciendo mal.

**Comment by Arcoirisky** [comment]
Holaa, no soy ayudante pero lo que estás haciendo es buscar aquel atributo name de la relación tracks que sea igual a "S" O:

**Comment by Mdelaf** [comment]
Hola, 

Cuando usas una condición de igualdad (`=`) lo que estas haciendo es buscar las filas donde el campo es exactamente igual al _string_ que estás comparando. Como en la tabla `tracks` no hay ninguna fila cuya columna `name` sea igual a `"S"` no te devuelve ningún resultado.

Para esa consulta debes usar un operador que te permita comparar _strings_ con un determinado patrón. En [este enlace](https://www.tutorialspoint.com/sqlite/sqlite_like_clause.htm) puedes encontrar información sobre cómo hacerlo.

Saludos.
