### ISSUE TITLE
Actividad 3

### ISSUE THREAD

**Issue by josefaespnza** [Exploratorio-DCC-PUC/Syllabus-2018-2#6]
Hola es que creo que borre el archivo LOGS.txt, como puedo volver a la ultima version intente con git log pero no me resulta.

**Comment by Mdelaf** [comment]
Hola,

Si borraste el archivo desde la interfaz de usuario (click derecho, eliminar) puedes recuperarlo desde la papelera. 

Si borraste el archivo usando el comando `rm` creo que no hay una manera sencilla de recuperarlo. En este caso tendrías que volver a correr el archivo `actividad2.pyc` para que vuelva a crear todos los archivos y luego repetir los pasos que seguiste en la actividad 2.

Usar `git log` o intentar volver a un _commit_ anterior no te va a servir porque nunca creaste un _commit_ con ese archivo.  

Saludos.
