### ISSUE TITLE
[TC2] Cardinalidad en diagrama E/R

### ISSUE THREAD

**Issue by malopez16** [Exploratorio-DCC-PUC/Syllabus-2018-2#60]
Hola! Se va a evaluar la simbología de cardinalidad de las componentes de la bdd o sólo unimos con líneas (sin flechas)?

Gracias :)

**Comment by Dalal15** [comment]
Hola,

Lo que se evualará será que la cardinalidad sea correcta. Si deseas solo unir con líneas y colocar la cardinalidad donde corresponda no habrá problemas. Si quieres ocupar las flechas también estará correcto.

Saludos!

**Comment by malopez16** [comment]
gracias!
