### ISSUE TITLE
TC2 Vistas en SQLite

### ISSUE THREAD

**Issue by Arcoirisky** [Exploratorio-DCC-PUC/Syllabus-2018-2#61]
Hola! ¿Podemos crear vistas para las consultas? O:

**Comment by diflores** [comment]
Hola,

En lo personal, considero que crear vistas es un poco exagerado y va bastante más allá de lo que se espera que pongan en práctica en esta tarea. Sin embargo, eres libre de utilizar vistas en tu solución. Asegúrate de detallar bien lo que hiciste (cómo/con qué creaste la vista, qué consulta en SQL empleaste para obtener lo pedido) en el README destinado a esa parte de la tarea.

¡Mucho éxito! 🇨🇱

**Comment by Arcoirisky** [comment]
Sí perdón akndksks me di cuenta que sobrepensé la pregunta xDD Lo logré sin vistas amdnsm
