### ISSUE TITLE
TC2 Consulta 3

### ISSUE THREAD

**Issue by mjabalos** [Exploratorio-DCC-PUC/Syllabus-2018-2#63]
Hola, tengo un problema con la tabla TRACKS, me tira error al intentar llamar la columna Miliseconds (SELECT TRACKS.Miliseconds). Me dice que no existe, y si estoy llamando la tabla en el FROM.
Con esto no puedo retornar lo que me piden ni trabajar sobre el atributo para encontrar el valor maximo.

**Comment by Arcoirisky** [comment]
¿No es millisecond? Con LL?

**Comment by mjabalos** [comment]
al menos en el enunciado me aparece con una, voy a tratar igual

**Comment by mjabalos** [comment]
jajaja ahi me funciona, gracias!
