### ISSUE TITLE
Control

### ISSUE THREAD

**Issue by iraraya** [Exploratorio-DCC-PUC/Syllabus-2018-2#65]
Hola
¿entra la materia de redes de la clase de sistemas operativos en el control del viernes?
saludos y gracias

**Comment by Mdelaf** [comment]
No, no entra.

Saludos.

**Comment by vtunon7** [comment]
Hola!
Es necesario que en el output exista una fila con la suma total de todo lo recaudado por las películas o solo debe aparecer cada película con su respectiva recaudación.

**Comment by ValentinaAlvarezG** [comment]
Hola!

Solo cada película con su respectica recaudación

**Comment by perezpefaur** [comment]
Entonces "Título y suma recaudada de todas las películas que empiecen con la letra ’A’ mayúscula" estaría mal redactado? seria :
Título y suma recaudada de cada una de las películas que empiecen con la letra ’A’ mayúscula

**Comment by ValentinaAlvarezG** [comment]
Así como mal redactado no, porque son todas las películas que empiecen con A, pero si te acomoda más con cada película, bacan.
