### ISSUE TITLE
busco compañero

### ISSUE THREAD

**Issue by siescobedo** [Exploratorio-DCC-PUC/Syllabus-2018-2#69]
aun no tengo compañero para la tg2, a alguien más le falta?

**Comment by pongmaniatic** [comment]
Hola, a mi me falta tambien, mi email es eimorales@uc.cl

**Comment by Jiruiz2** [comment]
Hola,

El principal inconveniente que presentan es en cuanto a la eficiencia que tienen para retornar los datos, ya que, cada vez que se ejecuta una consulta, se recorren todas las filas de las tablas involucradas revisando cuales cumplen las condiciones de retorno. Por lo tanto, por cada anidación se volvería a recorrer la tabla, lo cual cuando estamos con tablas de cientos de miles de datos se vuelve muy costoso, por lo que queremos acostumbrarlos desde ya a evitar las consultas anidadas cuando sea posible.

Saludos

**Comment by Coolgatty** [comment]
Y si dicha consulta anidada trabaja con tablas diferentes? Algo como 

SELECT * FROM Proyectos WHERE pid IN (SELECT pid FROM RecursosProyectos)

Y cual seria la alternativa?
Lo digo porque estoy dando bases de datos y justo tengo una entrega muy parecida a esta tarea.

**Comment by Jiruiz2** [comment]
Hola,

No puedo responderte eso porque es fácilmente extrapolable a preguntas de la tareas. Además el fin de la tarea es que resuelvan estás dudas ustedes mismos.

Cabe señalar que todas las consultas pueden hacerse sin consultas anidadas.

Saludos.
