### ISSUE TITLE
Como borrar 

### ISSUE THREAD

**Issue by Dnpoblete** [Exploratorio-DCC-PUC/Syllabus-2018-2#7]
Hola, me equivoque en una parte de la tarea y quería saber como puedo hacer para borrar algo que ya subí a mi repositorio o si se puede volver a como estaba al principio o algo asi.
Gracias

**Comment by Mdelaf** [comment]
Hola, 

Los _commits_ que subiste al repositorio de Github no pueden eliminarse (recuerda que la gracia es poder ver todos los estados por los que ha pasado tu repositorio). 

Si hiciste algo mal, puedes crear otro _commit_ arreglando el problema y en el comentario del _commit_ deberías especificar qué es lo que estás arreglando. Nosotros nos fijaremos en eso a la hora de corregir la tarea.

Saludos.
