### ISSUE TITLE
busco compañero TG2

### ISSUE THREAD

**Issue by ploello** [Exploratorio-DCC-PUC/Syllabus-2018-2#70]

**Comment by dicampusano** [comment]
Hola, yo tampoco tengo compañero. Seamos juntos, te parece?

**Comment by ploello** [comment]
Me parece, este es mi telefono +56971239476


ATTE: Pablo Torres
-------- Mensaje original --------De: dicampusano <notifications@github.com> Fecha: 4/10/18  10:01  (GMT-04:00) A: Exploratorio-DCC-PUC/Syllabus <Syllabus@noreply.github.com> CC: Pablo Torres <patorres7@uc.cl>, Author <author@noreply.github.com> Asunto: Re: [Exploratorio-DCC-PUC/Syllabus] busco compañero TG2 (#70) 
Hola, yo tampoco tengo compañero. Seamos juntos, te parece?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Exploratorio-DCC-PUC/Syllabus","title":"Exploratorio-DCC-PUC/Syllabus","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Exploratorio-DCC-PUC/Syllabus"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dicampusano in #70: Hola, yo tampoco tengo compañero. Seamos juntos, te parece?"}],"action":{"name":"View Issue","url":"https://github.com/Exploratorio-DCC-PUC/Syllabus/issues/70#issuecomment-427009435"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Exploratorio-DCC-PUC/Syllabus/issues/70#issuecomment-427009435",
"url": "https://github.com/Exploratorio-DCC-PUC/Syllabus/issues/70#issuecomment-427009435",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Exploratorio-DCC-PUC/Syllabus] busco compañero TG2 (#70)",
"sections": [
{
"text": "",
"activityTitle": "**dicampusano**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@dicampusano",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Exploratorio-DCC-PUC/Syllabus\",\n\"issueId\": 70,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Exploratorio-DCC-PUC/Syllabus\",\n\"issueId\": 70\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Exploratorio-DCC-PUC/Syllabus/issues/70#issuecomment-427009435"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 387651496\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by ploello** [comment]
Perfecto, mi mail es patorres7@uc.cl
