### ISSUE TITLE
Compañero TG2

### ISSUE THREAD

**Issue by mjabalos** [Exploratorio-DCC-PUC/Syllabus-2018-2#71]
Ando buscando compañero para la tarea, alguien en las mismas?
mi mail es mjabalos@uc.cl

**Comment by Serazlog** [comment]
Yo, mi mail es slecaros@uc.cl

**Comment by slecaros** [comment]
Yo, mi mail es slecaros@uc.cl

**Comment by mjabalos** [comment]
Pucha disculpa, ya me contacto otro compadre, voy a sacar el issue.
Suerte igual
