### ISSUE TITLE
Parte 2

### ISSUE THREAD

**Issue by matumartinez** [Exploratorio-DCC-PUC/Syllabus-2018-2#72]
Hola,

al entrenar el modelo knn si me entrega un puntaje, pero me aparece la siguiente advertencia:

/Users/matiasmartinez/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

¿Qué significa y cómo lo arreglo?

Gracias de antemano

PD: el input que usé fue el que nos dieron en la ayudantía:

knn_1 = KNeighborsClassifier(n_neighbors=5)

knn_1.fit(training_data, training_labels)

knn_1.score(test_data, test_labels)

**Comment by IchottMano** [comment]
@matumartinez Hola!

Podrías por favor especificar la forma de tus datos? (Qué son?)

Saludos!

**Comment by mjcadile** [comment]
Me pasa lo mismo! lo solucioné poniendo 
en vez de:
knn_1.fit(training_data, training_labels)
agregar
knn_1.fit(training_data, training_labels.values.ravel())

**Comment by matumartinez** [comment]
@mjcadile gracias, eso arregló el problema
