### ISSUE TITLE
Busco compañer@ TG2

### ISSUE THREAD

**Issue by aiduran** [Exploratorio-DCC-PUC/Syllabus-2018-2#73]
Hola! Estoy buscando compañer@ para poder realizar la TG2.

**Comment by Serazlog** [comment]
Yo puedo, mi mail es slecaros@uc.cl

**Comment by slecaros** [comment]
Yo puedo, mi mail es slecaros@uc.cl

**Comment by slecaros** [comment]
Hola, avisame cualquier cosa para buscar otro compañero sino puedes
