### ISSUE TITLE
Parte 2

### ISSUE THREAD

**Issue by mjcadile** [Exploratorio-DCC-PUC/Syllabus-2018-2#75]
Hola, al intentar ocupar KNN y entrenar el modelo, me pide obviamente training_data y training_labels, que en la ayudantía provenían de digits["data"] y digits["target"] respectivamente. El problema es que estos vendrían siendo atributos de este dataset precargado en sklearn... pero ahora que necesito mi "data" y mi "target" del csv de vinos, cuál vendría siendo mi target? la calidad? y mi data vendrían siendo todas las otras características de los vinos menos la calidad?
De antemano gracias

**Comment by IchottMano** [comment]
@mjcadile Hola!

Efectivamente, tu target es la calidad mientras que los datos son el resto de las cualidades excepto por el identificador.

Saludos!
