### ISSUE TITLE
Parte 2

### ISSUE THREAD

**Issue by tcperez** [Exploratorio-DCC-PUC/Syllabus-2018-2#78]
Hola!!

En la parte 2, realizando el código para el módelo KKN
 al correr : 

>knn_1.score(X, Y)

el programa me arroja el siguiente error:

Input contains NaN, infinity or a value too large for dtype('float64').

¿alguna idea de como arreglarlo o qué podría ser? Gracias de antemano

**Comment by Mdelaf** [comment]
El error dice claramente que en alguno de los input que le estás entregando al método `.score` (probablemente sea el input `X`) contiene un valor no numérico o un infinito en un atributo que debiera solo tener valores decimales. 

Revisa tu matriz `X` y verifica que en todas las columnas no haya valores `N/A` ni valores vacíos. 

Recuerda que el pre-procesamiento que se pide en la Parte 1 debes hacerlo sobre todo el conjunto de datos (no solo los datos de training), y debes asegurarte de quitar o reemplazar todos aquellos valores que no estén bien definidos. 

Saludos.
