### ISSUE TITLE
Parte 1 TG2

### ISSUE THREAD

**Issue by mpsubiabre** [Exploratorio-DCC-PUC/Syllabus-2018-2#81]
Borre los NaN y  luego normalize los datos con el comando sugerido, menos los "id" y "calidad". Luego de pasarlo a dos dimensiones use el comando pd.concat([df1,df2], axis=1) para unir los datos normalizados con los "id" y "calidad" pero me salen NaN, ¿Que puede ser?

**Comment by Mdelaf** [comment]
Probablemente es por la misma razón que se menciona en la respuesta de [esta issue](https://github.com/Exploratorio-DCC-PUC/Syllabus/issues/79). Los índices de ambos DF no coinciden y por eso aparecen los NaN. 

Como se menciona en #79 puedes agregar la calidad manualmente haciendo:
```
df_pca["calidad"] = df_original["calidad"].values
```

Avisa cómo te va.

**Comment by mpsubiabre** [comment]
me sale esto ahora 
![image](https://user-images.githubusercontent.com/42593773/46839483-87ae4880-cd94-11e8-820f-1e56f07cbfde.png)

**Comment by Mdelaf** [comment]
Intenta hacer lo que te dice el error, es decir:
```
df_pca.loc[:, "calidad"] = df_original["calidad"].values
```
