### ISSUE TITLE
TG2

### ISSUE THREAD

**Issue by josefaespnza** [Exploratorio-DCC-PUC/Syllabus-2018-2#82]
Hola, podrían subir el enunciado con los puntajes, en una ayudantia mencionaron que lo podian hacer. Saludoss

**Comment by Dalal15** [comment]
Hola!

Ya se encuentra actualizado el enunciado con los puntajes de cada parte.

- Parte 1: 1 punto
- Parte 2: 0,8 puntos
- Parte 3: 0,7 puntos
- Parte 4: 1,5 puntos
- Parte 5: 2 puntos

Saludos!
