### ISSUE TITLE
Problema con altair 

### ISSUE THREAD

**Issue by mpbosnic** [Exploratorio-DCC-PUC/Syllabus-2018-2#84]
Hola, cuando intento instalar la librería altair en el notebook jupyter mediante
`import altair as alt`
me tira el siguiente error:
`ModuleNotFoundError: No module named 'altair'`.
¿Que debo hacer para solucionarlo?
Gracias!

**Comment by diflores** [comment]
Hola,

La instalación debes realizarla por consola con `pip install altair` (o `pip3 install altair` si estás en MacOS o Linux). Cuando ya esté instalada, podrás usar `import altair as alt`.

**Comment by mpbosnic** [comment]
Gracias!
