### ISSUE TITLE
confusion matrix

### ISSUE THREAD

**Issue by cncosta** [Exploratorio-DCC-PUC/Syllabus-2018-2#85]
al imprimir la confusion matrix para ver uno de los resultados de mis predicciones me aparecen los valores de 0 a 6 ,  en vez de 3 a 9 , esto se puede arreglar ?
![captura de pantalla 2018-10-13 a la s 18 33 57](https://user-images.githubusercontent.com/42576884/46910196-aa686a80-cf16-11e8-9d8c-95026651fc58.png)

**Comment by diflores** [comment]
Hola,

Sí se puede. Lo que se me ocurre es que busques sobre cómo cambiar el index de un DataFrame, para poder asignarle una lista del 3 al 9 (busca sobre `set_index` en pandas). El nombre de las columnas puedes cambiarlo con `df.columns = [lista de nombres de columnas]`.

¡Saludos!
