### ISSUE TITLE
Parte 5 pregunta 3

### ISSUE THREAD

**Issue by mpbosnic** [Exploratorio-DCC-PUC/Syllabus-2018-2#87]
Hola, no entiendo que debo hacer con la información:

> Considere que un vino es bueno cuando su calidad es mayor o igual a 6.

Gracias!

**Comment by Dalal15** [comment]
Debes responder las preguntas que aparecen en la **pregunta 3** con esa información. Primero debes investigar qué significan  _precision_ y _recall_ . Luego debes calcular estas métricas para cada modelo, explicando sus resultados al predecir si un vino era bueno o malo.

**Comment by mpbosnic** [comment]
Osea debo crear una dataframe "nuevo" con la calidad expresada en "bueno" o "malo" en vez de números?

**Comment by Dalal15** [comment]
No es necesario, ya sabes que cuando la calidad de un vino es mayor o igual a 6 es un vino bueno. Puedes manejar todo con números y en el análisis explicar qué significan.

**Comment by mpsubiabre** [comment]
Podemos hacerlo manualmente? es decir a partir de los datos entregados por la matriz de confusión calcular las métricas con conteo?

**Comment by Mdelaf** [comment]
Claro, esa es la idea. A partir de la matriz de confusión puedes obtener los valores para calcular _precision_ y _recall_ como si se tratase de una clasificación binaria. 

Explica bien en tu informe cómo lo hiciste.

**Comment by mpsubiabre** [comment]
Perfecto, gracias!
