### ISSUE TITLE
Tarea 2 Parte 3

### ISSUE THREAD

**Issue by mjcadile** [Exploratorio-DCC-PUC/Syllabus-2018-2#88]
Hola, tengo una duda sobre los scores que me arrojan los modelos, ya que ocupé accuracy_score (de sklearn_metrics) para ver que tan precisos son mis modelos y me arrojan un puntaje de no más de 0,5...
No se si es normal que me arroje tan baja precisión o quizás estoy haciendo algo mal
Gracias

**Comment by pstassara** [comment]
Yo estoy obteniendo valores similares y tengo la misma duda.

**Comment by Mdelaf** [comment]
Hola,

Les recomiendo leer [esta issue](https://github.com/Exploratorio-DCC-PUC/Syllabus/issues/80) donde se explica detalladamente por qué el score puede ser bajo en este dataset particular, y qué otras métricas podrían usar. 

Saludos.

**Comment by fivaldivia** [comment]
Hola, nosotras ocupamos la métrica diff que recomiendan usar y también nos dan valores cercanos a 0,5.. que no varían mucho mas alto, llegan a valores de 0,58 máximo.

**Comment by Mdelaf** [comment]
Hola @fivaldivia 

Para evaluar el rendimiento de clasificación uno tiene que usar métricas y entender qué es lo que representa el valor de esa métrica, si no no tiene mucho sentido. 

El score representa qué porcentaje de los datos se clasificaron correctamente. Por ser un porcentaje toma siempre valores entre 0 y 1. A nosotros nos gustaría que esté más cerca del 1, porque eso significaría que el 100% de los datos fueron clasificados de manera correcta. 

El problema de usar score en este dataset es que un dato que tenía valor real 8 y nuestro clasificador predijo 7 se considera mal clasificado. Sin embargo uno no diría que la clasificación fue del todo incorrecta, porque estuvo muy cerca (entre calidad 7 y 8 no hay mucha diferencia).

Para este tipo de problemas usamos funciones de pérdida, donde la métrica nos indica qué tanto se aleja la predicción del valor real. El valor numérico de una función de pérdida no tiene nada que ver ni es comparable al score porque miden cosas totalmente distintas. Cuando una función de pérdida tiene valor cero significa que el valor predicho es exactamente igual al valor real, y por lo tanto ese es el caso ideal que nos gustaría tener. A medida que va aumentando significa que el valor predicho se aleja más del valor real. 

Entendiendo esto, obtener 0.5 en su función de pérdida significa que en promedio, la clase predicha está a distancia 0.5 de la clase real (probablemente a muchos les predijo la calidad exacta y a otros les predijo una calidad un número mayor o un número menor), lo que es un excelente resultado.
