### ISSUE TITLE
git status

### ISSUE THREAD

**Issue by adbakulic** [Exploratorio-DCC-PUC/Syllabus-2018-2#9]
Hola,
Me pasó que al agregar un archivo de texto con add después al revisar el status no me aparecía como modificación, no se si se habrá agregado bien.

**Comment by Mdelaf** [comment]
Hola,

Cuando tu creas, eliminas o modificas un archivo en tu repositorio, y luego haces `git status`, entonces te debería aparecer ese archivo en la lista de archivos no listo para hacer commit (_not ready to commit_), en color rojo. 

Cuando tu haces `git add <archivo>` a uno de los archivos modificados y luego haces `git status`, este debería aparecer en la lista de archivos listos para hacer commit (_ready to commit_), en color verde.

Por último, cuando haces  `git commit` y luego `git status` los archivos que estaban en _ready to commit_ deberían desaparecer de esa lista, y al principio del mensaje debería decirte que estás a un commit delante de `<<origin/master>>`.

Te recomiendo que revises la [guía de git, particularmente el ejemplo introductorio](https://github.com/Mdelaf/git-introduction-guide#example) ya que ahí puedes ver qué te debería mostrar `git status` en cada paso.

**Comment by adbakulic** [comment]
gracias!!
