### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by iraraya** [Exploratorio-DCC-PUC/Syllabus-2018-2#91]
Hola! No me queda claro en la parte 4 si el gráfico de clustering debe ser 2D o 3D, considerando que dice que se incluya la calidad en los gráficos. Además, quería saber si se debe hacer con los datos simplemente reducidos a dos dimensiones o además de eso, escalados.
Gracias!

**Comment by Mdelaf** [comment]
Primero debes usar PCA para llevar tus datos a 2D. Luego debes graficar esos datos en el plano y mostrarlos por color según su etiqueta. Por último debes aplicar los algoritmos de clustering sobre los mismos datos (en 2D) y ver si los clusters que te encuentra se corresponden más o menos a los datos según sus etiquetas.

En la ayudantía 5 se hizo un ejercicio muy similar, puedes revisarlo ahí.

**Comment by NelsonIMA** [comment]
Una consulta, solo para confirmar, con etiqueta te refieres a la calidad cierto?

Gracias de antemano :)

**Comment by Mdelaf** [comment]
Si!

**Comment by NelsonIMA** [comment]
Gracias!

Otra consulta, es normal (o va por buen camino) que al visualizar la transformación por medio de Altair se vea así? 

![captura de pantalla 2018-10-15 a la s 13 06 05](https://user-images.githubusercontent.com/42616922/46963169-562acb00-d07b-11e8-9243-b0f64e11d6f8.png)

**Comment by iraraya** [comment]
Me pasa lo mismo, es como si no se pareciera nada a los clusterings

**Comment by Mdelaf** [comment]
Si hiciste todo bien y llegaste a ese resultado, es posible que al hacer la reducción de dimensionalidad con PCA se esté perdiendo mucha información de los datos, y por lo tanto en la representación 2D no se vea bien la separación de las clases.

Lo que más importa es la explicación que den de los resultados, y digan por qué podría estar viéndose así.

**Comment by iraraya** [comment]
Una última pregunta. ¿Cuál es el parámetro que hay que variar en meanshift? Ya que al parecer, el número de clusters los calcula solo, y no encuentro otra cosa para manipular
Gracias!

**Comment by Mdelaf** [comment]
En la documentación de `scikit-learn` puedes ver los parámetros que recibe Meanshift, escoge uno que sea relevante y justifica en las preguntas qué significa ese parámetro, por qué es relevante, y como afecta modificarlo para la obtención de los resultados.

**Comment by NelsonIMA** [comment]
Gracias por la respuesta :)

Otra consulta, para graficar los clustering es obligatorio usar Altair?, ya que lo menciona para la parte de la transformación, no explicitamente para los Clusters 
![captura de pantalla 2018-10-16 a la s 11 00 10](https://user-images.githubusercontent.com/42616922/47021856-ab75e380-d132-11e8-9b30-da485ca5adce.png)

**Comment by Mdelaf** [comment]
La idea es que se haga todo con Altair. 

Saludos.

**Comment by fnquinteros** [comment]
Hola, investigando un poco me encontré con que el algoritmo MeanShift es "no paramétrico", pero que necesita recibir un ancho de banda. No acabo de entender bien qué es el ancho de banda, pero sklearn lo estima por sí solo y, a mi parecer, no tiene mucho sentido estarlo cambiando porque sí. Es esta una justificación válida para no variar ningún parámetro al usar MeanShift?
