### ISSUE TITLE
Urgente repositorio

### ISSUE THREAD

**Issue by Dnpoblete** [Exploratorio-DCC-PUC/Syllabus-2018-2#93]
Hola hoy me meti al repositorio para ve como se veia lo que llevaba y no me carga el documento .ipynb, pero ayer si funcionaba, he hecho nuevos commit y lo he tratado de abrir de otros computadores y no carga.
Alguna idea de que puede ser o que puedo hacer? :(
Gracias

**Comment by nrrosenberg** [comment]
a mi me pasa lo mismo

**Comment by pstassara** [comment]
A mí también me pasa lo mismo.

**Comment by diflores** [comment]
Hola,
¿Pueden ser más específicos con su problema? ¿No les abre en la página o en localhost?

**Comment by Dnpoblete** [comment]
No me carga el repositorio de github en internet.

**Comment by diflores** [comment]
@Dnpoblete, @nrrosenberg, @pstassara Estimados, parece ser un error en la página de GitHub. Mientras funcione en sus computadores localmente, todo bien, pues lo que haremos nosotros para corregir es clonar sus repositorios y cargar los _notebooks_ en nuestros computadores.
Saludos.
