### ISSUE TITLE
Archivo.tex

### ISSUE THREAD

**Issue by amaiajuanchuto** [Exploratorio-DCC-PUC/Syllabus-2018-2#95]
En la parte 1 de la tarea chica 3, sale que ademas del pdf tenemos que adjuntar el archivo.tex.
No se como descargar ese archivo, solo pude descargar el pdf pero no veo la opción de descargar del otro, por favor si me pudieran ayudar, muchas gracias.

**Comment by Jiruiz2** [comment]
Si estas en overleaf, en la parte izquierda arriba está menú, si lo clickeas te da la opción de descargar la fuente(source) o el pdf. Debes descargar la fuente para obtener lo que quieres.
![image](https://user-images.githubusercontent.com/26437497/47188692-74a8f480-d30f-11e8-8e62-2d8e7e2496bb.png)

**Comment by NelsonIMA** [comment]
Hay algun archivo .tex como base para la parte 1? En caso de, en donde esta? 
Gracias :)

**Comment by Mdelaf** [comment]
En el enunciado, sección **Entrega** están las instrucciones y un link al archivo que deben usar como base para esa pregunta.

**Comment by NelsonIMA** [comment]
Muchas gracias!
