### ISSUE TITLE
Duda TC3 "Definición formal"

### ISSUE THREAD

**Issue by malopez16** [Exploratorio-DCC-PUC/Syllabus-2018-2#96]
Hola!
con "definición formal" se refieren al mismo nivel de detalle del ejemplo del enunciado?

Igual se solicita "definición formal" de q<sub>0</sub>, y eso no me hace mucho sentido. A qué se refieren con eso? 

gracias.

**Comment by Mdelaf** [comment]
Hola,

Sí, el ejemplo del enunciado es una muestra de lo que sería la definición formal. En ayudantía también vimos un ejemplo un poco más complejo. 

Con respecto a q<sub>0</sub> solo se espera que menciones cuál es tu estado inicial, que debe ser uno de los elementos en el conjunto Q.

**Comment by malopez16** [comment]
Ok. Gracias!
