### ISSUE TITLE
Alfabeto arbitrario

### ISSUE THREAD

**Issue by Arcoirisky** [Exploratorio-DCC-PUC/Syllabus-2018-2#97]
Se refiere de a-z sin mayusculas ni números/signos entre medio?

**Comment by iraraya** [comment]
También con respecto al alfabeto y dado que no lo podemos suponer, cómo se asigna en una transición que "a" sea cualquier letra de éste? Se pone una condición?

**Comment by Mdelaf** [comment]
> Se refiere de a-z sin mayusculas ni números/signos entre medio?

No, se refiere a conjunto cualquiera que no puedes suponer. Es decir podría ser el conjunto `{a, b, c}` o `{0, 1, 2}` o `{a, b, c, d, e, f}` o cualquier otro. Lo que importa es que tu definición matemática no dependa de un alfabeto específico. 

> También con respecto al alfabeto y dado que no lo podemos suponer, cómo se asigna en una transición que "a" sea cualquier letra de éste? Se pone una condición?

Usando [cuantificadores lógicos](https://es.wikipedia.org/wiki/Cuantificador) sobre conjuntos.
